import sqlite3
from datetime import datetime

def init_sst_db(con, ensure_cols, ensure_sedes_mpd_cols, get_db):
    
    def ensure_sst_general_table(con):
        con.execute('\n        CREATE TABLE IF NOT EXISTS sst_general(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            sede_codigo TEXT,             -- S01, S02, ...\n            tipo TEXT NOT NULL,           -- prevencion / no_conformidad / informe\n            titulo TEXT,\n            detalle TEXT,\n            estado TEXT                   -- ABIERTO / CERRADO / EN_REVISION\n        )\n        ')
    def ensure_sst_plan_tables(con):
        con.execute("\n            CREATE TABLE IF NOT EXISTS sst_objetivos(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                sede_codigo TEXT,\n                codigo TEXT,\n                titulo TEXT NOT NULL,\n                horizonte_meses INTEGER,\n                descripcion TEXT,\n                fecha_inicio TEXT,\n                fecha_fin TEXT,\n                estado TEXT,\n                prioridad TEXT,\n                creado_en TEXT DEFAULT (datetime('now'))\n            )\n        ")
        con.execute("\n            CREATE TABLE IF NOT EXISTS sst_objetivo_acciones(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                objetivo_id INTEGER NOT NULL,\n                nombre TEXT NOT NULL,\n                fase TEXT,\n                responsable_area TEXT,\n                fecha_inicio TEXT,\n                fecha_fin TEXT,\n                estado TEXT,\n                indicador TEXT,\n                clasificacion TEXT,\n                justificacion TEXT,\n                avance_pct INTEGER,\n                evidencia_url TEXT,\n                notas TEXT,\n                orden INTEGER DEFAULT 0,\n                creado_en TEXT DEFAULT (datetime('now')),\n                FOREIGN KEY(objetivo_id) REFERENCES sst_objetivos(id)\n            )\n        ")
        ensure_cols(con, 'sst_objetivo_acciones', [('fase', 'TEXT'), ('indicador', 'TEXT'), ('clasificacion', 'TEXT'), ('justificacion', 'TEXT'), ('avance_pct', 'INTEGER')])
        con.commit()
    def ensure_materiales_table(con):
        con.execute("\n            CREATE TABLE IF NOT EXISTS materiales_stock(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                categoria TEXT NOT NULL,\n                item TEXT NOT NULL,\n                unidad TEXT NOT NULL,\n                cantidad REAL DEFAULT 0,\n                objetivo REAL,\n                observaciones TEXT,\n                creado_en TEXT DEFAULT (datetime('now'))\n            )\n        ")
        con.commit()
    def ensure_documentos_tables(con):
        con.execute("\n            CREATE TABLE IF NOT EXISTS documentos(\n                id_documento INTEGER PRIMARY KEY AUTOINCREMENT,\n                titulo TEXT NOT NULL,\n                tipo_documento TEXT NOT NULL DEFAULT 'documento_general',\n                descripcion TEXT,\n                fecha TEXT,\n                autor TEXT,\n                archivo_url TEXT,\n                estado TEXT NOT NULL DEFAULT 'borrador',\n                creado_en TEXT DEFAULT (datetime('now'))\n            )\n        ")
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_sedes(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                sede_codigo TEXT NOT NULL,\n                UNIQUE(id_documento, sede_codigo)\n            )\n        ')
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_agentes(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                id_agente INTEGER NOT NULL,\n                UNIQUE(id_documento, id_agente)\n            )\n        ')
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_vehiculos(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                patente TEXT NOT NULL,\n                UNIQUE(id_documento, patente)\n            )\n        ')
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_sst(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                tipo_evento TEXT,\n                id_evento INTEGER,\n                UNIQUE(id_documento, tipo_evento, id_evento)\n            )\n        ')
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_tags(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                tag TEXT NOT NULL,\n                UNIQUE(id_documento, tag)\n            )\n        ')
        con.execute('\n            CREATE TABLE IF NOT EXISTS documentos_destino(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                id_documento INTEGER NOT NULL,\n                destino TEXT NOT NULL,\n                UNIQUE(id_documento, destino)\n            )\n        ')
        con.execute('CREATE INDEX IF NOT EXISTS idx_documentos_tipo_estado ON documentos(tipo_documento, estado)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_documentos_fecha ON documentos(fecha)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_doc_sedes_sede ON documentos_sedes(sede_codigo)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_doc_agentes_agente ON documentos_agentes(id_agente)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_doc_vehiculos_patente ON documentos_vehiculos(patente)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_doc_tags_tag ON documentos_tags(tag)')
        con.execute('CREATE INDEX IF NOT EXISTS idx_doc_destino_dest ON documentos_destino(destino)')
        con.commit()
    def asegurar_tabla_limpieza():
        con = get_db()
        cur = con.cursor()
        cur.execute('\n            CREATE TABLE IF NOT EXISTS sedes_limpieza (\n                cod_sede            TEXT PRIMARY KEY,\n                agente_id           INTEGER,\n                responsable         TEXT,\n                turno               TEXT,\n                frecuencia          TEXT,\n                observaciones       TEXT,\n                fecha_actualizacion TEXT\n            )\n        ')
        con.commit()
        con.close()
    def asegurar_tablas_planos():
        """
            Crea las tablas sedes_planos y sedes_infra si no existen.
            Usamos esta función SOLO para estos dos objetos.
            """
        con = get_db()
        cur = con.cursor()
        cur.execute('\n            CREATE TABLE IF NOT EXISTS sedes_planos (\n                id          INTEGER PRIMARY KEY AUTOINCREMENT,\n                cod_sede    TEXT NOT NULL,\n                tipo        TEXT NOT NULL,        -- analisis / depositos / evacuacion\n                archivo     TEXT NOT NULL,        -- nombre del archivo guardado\n                fecha_carga TEXT                 -- YYYY-MM-DD\n            )\n        ')
        cur.execute('\n            CREATE TABLE IF NOT EXISTS sedes_infra (\n                cod_sede             TEXT PRIMARY KEY,\n                oficinas             INTEGER DEFAULT 0,\n                salas_entrevistas    INTEGER DEFAULT 0,\n                banios               INTEGER DEFAULT 0,\n                espacios_comunes     INTEGER DEFAULT 0,\n                depositos            INTEGER DEFAULT 0,\n                personas             INTEGER DEFAULT 0,\n                m2_totales           REAL    DEFAULT 0,\n                m2_por_persona       REAL    DEFAULT 0,\n                personas_por_oficina REAL    DEFAULT 0\n            )\n        ')
        con.commit()
        con.close()
    def asegurar_tabla_limpieza():
        """Crea la tabla sedes_limpieza si no existe."""
        con = get_db()
        cur = con.cursor()
        cur.execute('\n            CREATE TABLE IF NOT EXISTS sedes_limpieza (\n                cod_sede           TEXT PRIMARY KEY,\n                agente_id          INTEGER,\n                responsable        TEXT,\n                turno              TEXT,\n                frecuencia         TEXT,\n                observaciones      TEXT,\n                protocolo_url      TEXT,\n                fecha_actualizacion TEXT\n            )\n        ')
        con.commit()
        con.close()
    def asegurar_tabla_aires():
        con = get_db()
        cur = con.cursor()
        cur.execute('\n            CREATE TABLE IF NOT EXISTS aires_mpd(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                sede_codigo TEXT NOT NULL,   -- S01, S02, S03...\n                ambiente    TEXT,            -- Ej: Mesa de entrada, Planta alta, Oficina 3\n                marca       TEXT,\n                modelo      TEXT,\n                tipo        TEXT,            -- Split, ventana, central, etc.\n                frigorias   INTEGER,\n                estado      TEXT,            -- OK, pendiente service, no funciona, etc.\n                fecha_instalacion      TEXT,\n                fecha_ultima_limpieza  TEXT,\n                frecuencia_meses       INTEGER,    -- cada cuántos meses limpiás\n                observaciones          TEXT\n            );\n        ')
        con.commit()
    def init_db():
        con = get_db()
        cur = con.cursor()
        cur.execute('\n        CREATE TABLE IF NOT EXISTS sedes_depositos(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            codigo_sede TEXT NOT NULL,   -- S01, S02, ...\n            codigo_local TEXT NOT NULL,  -- S01-P00-D01\n            descripcion TEXT NOT NULL,   -- Pasillo, Cocina, etc.\n            UNIQUE(codigo_local),\n            FOREIGN KEY(codigo_sede) REFERENCES sedes_mpd(codigo)\n        )\n        ')
        cur.execute('SELECT COUNT(*) FROM sedes_depositos')
        if cur.fetchone()[0] == 0:
            depositos_seed = [('S01', 'S01-P00-D01', 'Pasillo'), ('S01', 'S01-P00-D02', 'Sec Def General'), ('S01', 'S01-P00-D03', 'Audiencia 1'), ('S01', 'S01-P00-D04', 'Peritos'), ('S01', 'S01-P00-D05', 'Cocina'), ('S01', 'S01-P00-D06', 'Baño 1'), ('S01', 'S01-P00-D07', 'Baño 2'), ('S01', 'S01-P00-D08', 'Patio'), ('S01', 'S01-P00-D09', 'Audiencia 3'), ('S01', 'S01-P00-D10', 'Salud Mental'), ('S01', 'S01-P01-D11', 'Laura del Valle'), ('S01', 'S01-P01-D12', 'Secretaría General'), ('S01', 'S01-P01-D13', 'Def 3'), ('S01', 'S01-P01-D14', 'Def 1'), ('S01', 'S01-P01-D15', 'Dra Fernández'), ('S01', 'S01-P01-D16', 'Baño 3'), ('S01', 'S01-P01-D17', 'Dr. Salinas'), ('S01', 'S01-P01-D18', 'Defensa General'), ('S01', 'S01-P01-D19', 'Baño 4'), ('S01', 'S01-P01-D20', 'Pasillo'), ('S01', 'S01-P02-D21', 'Sala Reunión'), ('S01', 'S01-P02-D22', 'Def de Menores'), ('S01', 'S01-P02-D23', 'Def 2'), ('S01', 'S01-P02-D24', 'Dra López'), ('S01', 'S01-P02-D25', 'Def 4'), ('S01', 'S01-P02-D26', 'Dra Quintar'), ('S01', 'S01-P02-D27', 'Depósito'), ('S01', 'S01-P02-D28', 'Baño 5'), ('S01', 'S01-P02-D29', 'Dra Garay'), ('S01', 'S01-P02-D30', 'Pasillo'), ('S02', 'S02-P00-D01', 'Equipo Canetti'), ('S02', 'S02-P00-D02', 'Baño'), ('S02', 'S02-P00-D03', 'Dr Canetti'), ('S02', 'S02-P00-D04', 'Dr Elgoyhen'), ('S02', 'S02-P00-D05', 'Baño'), ('S02', 'S02-P00-D06', 'Equipo Dr Elgoyhen'), ('S02', 'S02-P00-D07', 'Dra Cortez'), ('S02', 'S02-P00-D08', 'Sajama'), ('S02', 'S02-P00-D09', 'Baño'), ('S02', 'S02-P00-D10', 'Equipo Menores'), ('S02', 'S02-P00-D11', 'Dra Sajama'), ('S02', 'S02-P00-D12', 'Equipo Dra Sajama'), ('S02', 'S02-P00-D13', 'Lescano Patricia'), ('S02', 'S02-P00-D14', 'Mesa de Entrada'), ('S02', 'S02-P00-D15', 'Baño'), ('S02', 'S02-P00-D16', 'Cocina'), ('S02', 'S02-P00-D17', 'Baño'), ('S02', 'S02-P00-D18', 'Equipo Dra Yapura'), ('S02', 'S02-P00-D19', 'Dra Yapura'), ('S02', 'S02-P00-D20', 'Baño'), ('S02', 'S02-P00-D21', 'Equipo Defensor 1'), ('S02', 'S02-P00-D22', 'Defensor 1'), ('S02', 'S02-P00-D23', 'Cocina'), ('S02', 'S02-P00-D24', 'Baño'), ('S02', 'S02-P00-D25', 'Equipo Defensor 2'), ('S02', 'S02-P00-D26', 'Defensor 2'), ('S02', 'S02-P00-D27', 'Dr Vilca Gaitán'), ('S02', 'S02-P00-D28', 'Equipo Def 5'), ('S02', 'S02-P00-D29', 'Equipo Dra Soria'), ('S02', 'S02-P00-D30', 'Dra Soria'), ('S02', 'S02-P00-D31', 'Baño'), ('S02', 'S02-P00-D32', 'Baño'), ('S02', 'S02-P00-D33', 'Dr Rivas'), ('S02', 'S02-P00-D34', 'Equipo Dr Rivas'), ('S02', 'S02-P00-D35', 'Pasillo'), ('S03', 'S03-P01-D01', 'Administrativos'), ('S03', 'S03-P01-D02', 'Defensor'), ('S03', 'S03-P01-D03', 'Baño 1'), ('S03', 'S03-P01-D04', 'Dr Elías'), ('S03', 'S03-P01-D05', 'Patio'), ('S03', 'S03-P01-D06', 'Cocina'), ('S03', 'S03-P01-D07', 'Sala Entrevista'), ('S03', 'S03-P01-D08', 'Dra Acuña'), ('S03', 'S03-P01-D09', 'Pasillo'), ('S03', 'S03-P01-D10', 'Baño 2')]
            cur.executemany('\n                INSERT INTO sedes_depositos (codigo_sede, codigo_local, descripcion)\n                VALUES (?,?,?)\n            ', depositos_seed)
        s02_seed = [('S02', 'S02-P00-D01', 'Equipo Canetti'), ('S02', 'S02-P00-D02', 'Ba¤o'), ('S02', 'S02-P00-D03', 'Dr Canetti'), ('S02', 'S02-P00-D04', 'Dr Elgoyhen'), ('S02', 'S02-P00-D05', 'Ba¤o'), ('S02', 'S02-P00-D06', 'Equipo Dr Elgoyhen'), ('S02', 'S02-P00-D07', 'Dra Cortez'), ('S02', 'S02-P00-D08', 'Sajama'), ('S02', 'S02-P00-D09', 'Ba¤o'), ('S02', 'S02-P00-D10', 'Equipo Menores'), ('S02', 'S02-P00-D11', 'Dra Sajama'), ('S02', 'S02-P00-D12', 'Equipo Dra Sajama'), ('S02', 'S02-P00-D13', 'Lescano Patricia'), ('S02', 'S02-P00-D14', 'Mesa de Entrada'), ('S02', 'S02-P00-D15', 'Ba¤o'), ('S02', 'S02-P00-D16', 'Cocina'), ('S02', 'S02-P00-D17', 'Ba¤o'), ('S02', 'S02-P00-D18', 'Equipo Dra Yapura'), ('S02', 'S02-P00-D19', 'Dra Yapura'), ('S02', 'S02-P00-D20', 'Ba¤o'), ('S02', 'S02-P00-D21', 'Equipo Defensor 1'), ('S02', 'S02-P00-D22', 'Defensor 1'), ('S02', 'S02-P00-D23', 'Cocina'), ('S02', 'S02-P00-D24', 'Ba¤o'), ('S02', 'S02-P00-D25', 'Equipo Defensor 2'), ('S02', 'S02-P00-D26', 'Defensor 2'), ('S02', 'S02-P00-D27', 'Dr Vilca Gait\xa0n'), ('S02', 'S02-P00-D28', 'Equipo Def 5'), ('S02', 'S02-P00-D29', 'Equipo Dra Soria'), ('S02', 'S02-P00-D30', 'Dra Soria'), ('S02', 'S02-P00-D31', 'Ba¤o'), ('S02', 'S02-P00-D32', 'Ba¤o'), ('S02', 'S02-P00-D33', 'Dr Rivas'), ('S02', 'S02-P00-D34', 'Equipo Dr Rivas'), ('S02', 'S02-P00-D35', 'Pasillo')]
        existing_s02 = {r[0] for r in cur.execute("SELECT codigo_local FROM sedes_depositos WHERE codigo_sede = 'S02'").fetchall()}
        missing_s02 = [row for row in s02_seed if row[1] not in existing_s02]
        if missing_s02:
            cur.executemany('\n                INSERT OR IGNORE INTO sedes_depositos (codigo_sede, codigo_local, descripcion)\n                VALUES (?,?,?)\n            ', missing_s02)
        cur.execute('\n        CREATE TABLE IF NOT EXISTS movimientos_mobiliario(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,              -- YYYY-MM-DD\n            item TEXT NOT NULL,               -- Ej: Escritorio, Silla, PC\n            cantidad REAL DEFAULT 1,\n\n            sede_origen   TEXT,\n            deposito_origen TEXT,\n            sede_destino    TEXT,\n            deposito_destino TEXT,\n\n            observaciones TEXT\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS sede_planos(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            codigo_sede TEXT NOT NULL,\n            tipo TEXT NOT NULL,      -- 'distribucion','depositos','evacuacion'\n            archivo TEXT NOT NULL,   -- nombre del archivo en /static/planos\n            activo INTEGER DEFAULT 1,\n            FOREIGN KEY(codigo_sede) REFERENCES sedes_mpd(codigo)\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS sede_inventario(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            codigo_sede TEXT NOT NULL,\n            item TEXT NOT NULL,\n            categoria TEXT,\n            ubicacion TEXT,\n            cantidad REAL,\n            observaciones TEXT,\n            FOREIGN KEY(codigo_sede) REFERENCES sedes_mpd(codigo)\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS eventos(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            titulo TEXT NOT NULL,\n            detalle TEXT,\n            color TEXT DEFAULT '#3B82F6',\n            fuente TEXT NOT NULL,         -- 'vehiculos','combustible','viajes','checklist'\n            ref_id TEXT                  -- patente o id relacionado\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_intendencia(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente TEXT NOT NULL,\n            rubro TEXT NOT NULL,\n            dias_feria INTEGER DEFAULT 0,\n            foto_url TEXT,\n            activo INTEGER DEFAULT 1\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS agentes_licencias(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            tipo TEXT NOT NULL,              -- vacaciones, enfermedad, etc.\n            fecha_desde TEXT NOT NULL,       -- YYYY-MM-DD\n            fecha_hasta TEXT NOT NULL,\n            observaciones TEXT,\n            estado TEXT DEFAULT 'APROBADA',  -- APROBADA / PENDIENTE / RECHAZADA\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_compensatorios_mov(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            fecha TEXT NOT NULL,            -- fecha de carga (YYYY-MM-DD)\n            tipo TEXT NOT NULL,             -- INICIAL / FERIA / HORAS / TOMA\n            dias REAL DEFAULT 0,\n            horas REAL DEFAULT 0,\n            periodo TEXT,                   -- Ej: Enero 2026\n            desde TEXT,                     -- para TOMA\n            hasta TEXT,                     -- para TOMA\n            observaciones TEXT,\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_documentacion(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            tipo TEXT NOT NULL,              -- carnet_conducir, dni, art, examen_medico, etc.\n            fecha_vencimiento TEXT NOT NULL, -- YYYY-MM-DD\n            observaciones TEXT,\n            estado TEXT,                     -- VIGENTE, VENCIDO, EN TRÁMITE, etc.\n            archivo TEXT,\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id),\n            UNIQUE(agente_id, tipo)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_asignaciones (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            sede_codigo TEXT NOT NULL,\n            fecha_desde TEXT NOT NULL,   -- YYYY-MM-DD\n            fecha_hasta TEXT,            -- opcional\n            observaciones TEXT,\n            estado TEXT,                 -- ACTIVA / HISTORICA / BAJA\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS mapa_ssj_puntos(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            tipo TEXT NOT NULL,              -- \'proveedor\' / \'tarea\' / \'pericia\' / \'otro\'\n            titulo TEXT NOT NULL,            -- nombre corto (ej: "Ferretería X", "Medición gas", etc.)\n            descripcion TEXT,                -- detalle libre\n            estado TEXT NOT NULL DEFAULT \'pendiente\',  -- \'pendiente\' / \'ejecutado\'\n            direccion TEXT,\n            lat REAL,\n            lng REAL,\n            fecha_alta TEXT NOT NULL,        -- YYYY-MM-DD\n            fecha_visita TEXT,               -- YYYY-MM-DD (cuando se ejecuta o se revisa)\n            contacto TEXT,                   -- opcional (tel/email)\n            referencia TEXT                  -- opcional (nro pedido, orden, expediente, etc.)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS equipo_interdisciplinario(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            nombre TEXT NOT NULL,\n            profesion TEXT NOT NULL,\n            activo INTEGER DEFAULT 1,\n            UNIQUE(nombre, profesion)\n        )\n        ')
        cur.execute('SELECT COUNT(*) FROM equipo_interdisciplinario')
        if cur.fetchone()[0] == 0:
            equipo_seed = [('Natalia Marcos', 'Asistente Social'), ('Rut Romero', 'Asistente Social'), ('Agustina Frias', 'Psicología'), ('Pamela Gareca', 'Médica'), ('Jose Moreno', 'Perito')]
            cur.executemany('\n                INSERT OR IGNORE INTO equipo_interdisciplinario(nombre, profesion)\n                VALUES (?,?)\n            ', equipo_seed)
        cur.execute("\n        CREATE TABLE IF NOT EXISTS combustible_precios(\n            tipo TEXT PRIMARY KEY,    -- 'nafta' / 'gasoil'\n            precio_litro REAL NOT NULL\n        )\n        ")
        cur.execute('SELECT COUNT(*) FROM combustible_precios')
        if cur.fetchone()[0] == 0:
            cur.executemany('\n                INSERT INTO combustible_precios(tipo, precio_litro)\n                VALUES (?,?)\n            ', [('nafta', 0), ('gasoil', 0)])
        cur.execute('\n        CREATE TABLE IF NOT EXISTS movimientos_mobiliario(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            sede_origen TEXT NOT NULL,    -- código S01, S02...\n            deposito_origen TEXT,         -- texto libre (Depósito 1, Oficina 2, etc.)\n            sede_destino TEXT NOT NULL,   -- código S01, S02...\n            deposito_destino TEXT,        -- texto libre\n            item TEXT NOT NULL,           -- qué mueble / equipo se mueve\n            cantidad REAL,                -- cuántas unidades\n            observaciones TEXT\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS vehiculos(\n            patente TEXT PRIMARY KEY,\n            codigo_interno TEXT UNIQUE,   -- G-01 / N-01\n            tipo TEXT NOT NULL,           -- G / N\n            modelo TEXT,\n            combustible TEXT NOT NULL,    -- gasoil/nafta\n            base_ciudad TEXT DEFAULT 'San Salvador de Jujuy',\n            color_tag TEXT DEFAULT '#5B5BEA',\n            activo INTEGER DEFAULT 1\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS vehiculo_estado(\n            patente TEXT PRIMARY KEY,\n            ultimo_service TEXT,\n            proximo_service TEXT,\n            ultimo_lavado TEXT,\n            proximo_lavado TEXT,\n            seguro_inicio TEXT,\n            seguro_vencimiento TEXT,\n            rtv_inicio TEXT,\n            rtv_vencimiento TEXT,\n            FOREIGN KEY(patente) REFERENCES vehiculos(patente)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS vehiculo_choferes(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            patente TEXT NOT NULL,\n            chofer_id INTEGER NOT NULL,\n            activo INTEGER DEFAULT 1,\n            UNIQUE(patente, chofer_id),\n            FOREIGN KEY(patente) REFERENCES vehiculos(patente),\n            FOREIGN KEY(chofer_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS obras_sede(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            codigo_sede TEXT NOT NULL,\n            titulo TEXT NOT NULL,\n            tipo TEXT,                     -- eléctrico, albañilería, pintura, etc.\n            prioridad TEXT DEFAULT 'Media',-- Alta / Media / Baja\n            estado TEXT DEFAULT 'PENDIENTE',   -- PENDIENTE / EN_CURSO / FINALIZADA\n            fecha_solicitud TEXT NOT NULL,     -- YYYY-MM-DD\n            fecha_inicio TEXT,\n            fecha_fin_prevista TEXT,\n            fecha_fin_real TEXT,\n            descripcion TEXT,\n            observaciones TEXT,\n            FOREIGN KEY(codigo_sede) REFERENCES sedes_mpd(codigo)\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS destinos(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            nombre TEXT NOT NULL UNIQUE,\n            activo INTEGER DEFAULT 1\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_incidentes(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            tipo TEXT NOT NULL,           -- incidente / accidente / casi_accidente, etc.\n            lugar TEXT,\n            descripcion TEXT,\n            consecuencia TEXT,            -- sin lesion, con lesion leve, etc.\n            acciones TEXT,                -- medidas tomadas\n            estado TEXT,                  -- ABIERTO / CERRADO\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_sst(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            tipo TEXT NOT NULL,           -- prevencion / no_conformidad / informe\n            titulo TEXT,\n            detalle TEXT,\n            estado TEXT,                  -- ABIERTO / CERRADO / EN_REVISION\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_desempeno(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            fecha TEXT NOT NULL,          -- YYYY-MM-DD\n            tipo TEXT NOT NULL,           -- evaluacion, observacion, reconocimiento, etc.\n            periodo TEXT,                 -- ej: 2025 - 1er semestre\n            calificacion INTEGER,         -- 1 a 5 (opcional)\n            observaciones TEXT,\n            estado TEXT,                  -- ABIERTO / CERRADO / HISTORICO\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute("\n        CREATE TABLE IF NOT EXISTS viajes(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,\n            patente TEXT NOT NULL,\n            chofer_id INTEGER,\n            agente_trasladado TEXT,\n            equipo_id INTEGER,            -- para equipo interdisciplinario\n            destino_id INTEGER,\n            origen TEXT DEFAULT 'San Salvador de Jujuy',\n            km_ini REAL DEFAULT 0,\n            km_fin REAL DEFAULT 0,\n            recorrido_km REAL DEFAULT 0,\n            largo INTEGER DEFAULT 0,\n            observaciones TEXT,\n            FOREIGN KEY(patente) REFERENCES vehiculos(patente),\n            FOREIGN KEY(chofer_id) REFERENCES agentes_intendencia(id),\n            FOREIGN KEY(equipo_id) REFERENCES equipo_interdisciplinario(id),\n            FOREIGN KEY(destino_id) REFERENCES destinos(id)\n        )\n        ")
        cur.execute('\n        CREATE TABLE IF NOT EXISTS combustible_cargas(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,\n            patente TEXT NOT NULL,\n            chofer_id INTEGER,\n            remito TEXT,\n            km_actual REAL DEFAULT 0,\n            litros REAL NOT NULL,\n            precio_litro REAL NOT NULL,\n            precio_total REAL NOT NULL,     -- cantidad en plata\n            notas TEXT,\n            FOREIGN KEY(patente) REFERENCES vehiculos(patente),\n            FOREIGN KEY(chofer_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS checklist_items(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            nombre TEXT NOT NULL UNIQUE,\n            activo INTEGER DEFAULT 1\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS checklist_registros(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            fecha TEXT NOT NULL,\n            patente TEXT NOT NULL,\n            chofer_id INTEGER,\n            tipo TEXT NOT NULL, -- salida / entrada\n            observaciones TEXT,\n            FOREIGN KEY(patente) REFERENCES vehiculos(patente),\n            FOREIGN KEY(chofer_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('\n        CREATE TABLE IF NOT EXISTS checklist_detalle(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            registro_id INTEGER NOT NULL,\n            item_id INTEGER NOT NULL,\n            ok INTEGER DEFAULT 1,\n            nota TEXT,\n            FOREIGN KEY(registro_id) REFERENCES checklist_registros(id),\n            FOREIGN KEY(item_id) REFERENCES checklist_items(id)\n        )\n        ')
        cur.execute('SELECT COUNT(*) FROM sedes_mpd')
        if cur.fetchone()[0] == 0:
            sedes = [('S01', 'Independencia 202', 'San Salvador de Jujuy', 'Independencia 202', -24.1872, -65.296, 'penal'), ('S02', 'San Pedro Civil - Penal Unificado', 'San Pedro de Jujuy', '', -24.2319, -64.8667, 'penal'), ('S03', 'Perico Penal', 'Perico', '', -24.3833, -65.1167, 'penal'), ('S04', 'Alto Comedero', 'San Salvador de Jujuy', '', -24.225, -65.266, 'juridico_social'), ('S05', 'Humahuaca Penal', 'Humahuaca', '', -23.205, -65.349, 'penal'), ('S06', 'Ledesma Penal y Menores Unificado', 'Libertador Gral. San Martín', '', -23.809, -64.79, 'penal'), ('S07', 'Palpalá Penal', 'Palpalá', '', -24.256, -65.21, 'penal'), ('S08', 'San Martín 137', 'San Salvador de Jujuy', 'San Martín 137', -24.1879, -65.2996, 'administracion'), ('S10', 'El Carmen Civil - Penal Unificado', 'El Carmen', '', -24.386, -65.279, 'juridico_social'), ('S11', 'Gorriti 791', 'San Salvador de Jujuy', 'Gorriti 791', -24.1879, -65.2996, 'juridico_social'), ('S12', 'Belgrano 284', 'San Salvador de Jujuy', 'Belgrano 284', -24.1879, -65.2996, 'equipo_interdisciplinario'), ('S13', 'San Martín 271', 'San Salvador de Jujuy', 'San Martín 271', -24.1879, -65.2996, 'menores_incapaces')]
            cur.executemany('\n                INSERT INTO sedes_mpd(codigo,nombre,ciudad,direccion,lat,lng,fuero)\n                VALUES (?,?,?,?,?,?,?)\n            ', sedes)
        cur.execute('SELECT COUNT(*) FROM agentes_intendencia')
        if cur.fetchone()[0] == 0:
            agentes = [('Carlos Vidaurre', 'mantenimiento', 0, None), ('Marcos Duran', 'mantenimiento', 0, None), ('Nestor Guerrero', 'mantenimiento', 0, None), ('Manuel Flores', 'mantenimiento', 0, None), ('Francisco Savio', 'mantenimiento', 0, None), ('Ignacio Baroni', 'choferes', 0, None), ('Mauro Vea Murguia', 'choferes', 0, None), ('Emiliano P. de la Puente', 'choferes', 0, None), ('Nahuel Amado', 'choferes', 0, None), ('Luis Cardozo', 'choferes', 0, None), ('Beatriz Castillo', 'limpieza', 0, None), ('Miriam Tejerina', 'limpieza', 0, None), ('Yolanda Solis', 'limpieza', 0, None), ('Mabel Alejo', 'limpieza', 0, None), ('Miguel Saldano', 'limpieza', 0, None), ('Flavia Gutierrez', 'limpieza', 0, None), ('Micaela Aima', 'limpieza', 0, None), ('Bustamante', 'limpieza', 0, None)]
            cur.executemany('\n                INSERT INTO agentes_intendencia(agente,rubro,dias_feria,foto_url)\n                VALUES (?,?,?,?)\n            ', agentes)
        cur.execute('\n        CREATE TABLE IF NOT EXISTS agentes_epp(\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            agente_id INTEGER NOT NULL,\n            tipo TEXT NOT NULL,              -- casco, zapato, arnés, herramienta, etc.\n            categoria TEXT,                  -- EPP / HERRAMIENTA\n            fecha_entrega TEXT NOT NULL,     -- YYYY-MM-DD\n            cantidad INTEGER DEFAULT 1,\n            observaciones TEXT,\n            estado TEXT,                     -- ENTREGADO / DEVUELTO / BAJA / PERDIDO\n            FOREIGN KEY(agente_id) REFERENCES agentes_intendencia(id)\n        )\n        ')
        cur.execute('SELECT COUNT(*) FROM equipo_interdisciplinario')
        if cur.fetchone()[0] == 0:
            equipo_seed = [('Natalia Marcos', 'Asistente Social'), ('Rut Romero', 'Asistente Social'), ('Agustina Frias', 'Psicología'), ('Pamela Gareca', 'Médica'), ('Jose Moreno', 'Perito')]
            cur.executemany('\n                INSERT OR IGNORE INTO equipo_interdisciplinario(nombre, profesion)\n                VALUES (?,?)\n            ', equipo_seed)
        cur.execute('SELECT COUNT(*) FROM vehiculos')
        if cur.fetchone()[0] == 0:
            vehiculos_seed = [('AE856GD', 'G-01', 'G', 'Ford Ranger', 'gasoil', 'San Salvador de Jujuy', '#5B5BEA'), ('AE856GE', 'G-02', 'G', 'Ford Ranger', 'gasoil', 'San Pedro de Jujuy', '#65BFF4'), ('AF277OA', 'G-03', 'G', 'Ford Ranger', 'gasoil', 'San Salvador de Jujuy', '#F64B94'), ('AG846FR', 'G-04', 'G', 'Renault', 'gasoil', 'San Pedro de Jujuy', '#8B5CF6'), ('AB946VK', 'N-01', 'N', 'Ford Ranger', 'nafta', 'San Salvador de Jujuy', '#3B82F6')]
            cur.executemany('\n                INSERT INTO vehiculos(patente,codigo_interno,tipo,modelo,combustible,base_ciudad,color_tag)\n                VALUES (?,?,?,?,?,?,?)\n            ', vehiculos_seed)
            for v in vehiculos_seed:
                cur.execute('INSERT INTO vehiculo_estado(patente) VALUES (?)', (v[0],))
        cur.execute('SELECT COUNT(*) FROM destinos')
        if cur.fetchone()[0] == 0:
            destinos_seed = [('San Salvador',), ('San Pedro',), ('Perico',), ('Palpalá',), ('Humahuaca',), ('Tilcara',), ('Abra Pampa',), ('La Quiaca',), ('El Carmen',), ('Ledesma',)]
            cur.executemany('INSERT INTO destinos(nombre) VALUES (?)', destinos_seed)
        cur.execute('SELECT COUNT(*) FROM checklist_items')
        if cur.fetchone()[0] == 0:
            items_seed = [('Luces',), ('Aceite',), ('Agua',), ('Rueda auxilio',), ('Botiquín',), ('Extintor',), ('Documentación',)]
            cur.executemany('INSERT INTO checklist_items(nombre) VALUES (?)', items_seed)
        cur.execute('SELECT COUNT(*) FROM combustible_precios')
        if cur.fetchone()[0] == 0:
            precios_seed = [('nafta', 1200.0), ('gasoil', 1400.0)]
            cur.executemany('\n                INSERT INTO combustible_precios(tipo, precio_litro)\n                VALUES (?, ?)\n            ', precios_seed)
    def init_db():
        con = get_db()
        cur = con.cursor()
        cur.execute("\n        CREATE TABLE IF NOT EXISTS asistidos(\n          id INTEGER PRIMARY KEY AUTOINCREMENT,\n          nombre TEXT NOT NULL,\n          barrio TEXT,\n          direccion TEXT,\n          referencia TEXT,\n          telefono TEXT,\n          lat REAL,\n          lng REAL,\n          estado TEXT NOT NULL DEFAULT 'NO_REALIZADA',\n          creado_en TEXT DEFAULT (date('now'))\n        )\n        ")
        ensure_sedes_mpd_cols(con)
        con.commit()
        con.close()
    def ensure_sst_ergonomia_table(con):
        con.execute("\n            CREATE TABLE IF NOT EXISTS sst_ergonomia(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                personal_id INTEGER NOT NULL UNIQUE,\n                codigo_sede TEXT NOT NULL,\n                nombre_apellido TEXT NOT NULL,\n                edad INTEGER DEFAULT 0,\n                correo TEXT,\n                descripcion_puesto TEXT DEFAULT 'Puesto completo de oficina',\n                tipo_silla TEXT DEFAULT 'Silla fija',\n                tipo_escritorio TEXT DEFAULT 'Escritorio de PC solo',\n                soporte_monitor TEXT DEFAULT 'Sin soporte de monitor',\n                oficina TEXT,\n                puntuacion_puesto INTEGER DEFAULT 0,\n                descripcion_salud TEXT,\n                puntuacion_salud INTEGER DEFAULT 0,\n                promedio REAL DEFAULT 0,\n                accion_tomar TEXT DEFAULT 'Programado',\n                observaciones TEXT,\n                actualizado_en TEXT DEFAULT (datetime('now'))\n            )\n        ")
        ensure_cols(con, 'sst_ergonomia', [('altura_monitor', 'TEXT'), ('espacio_piernas', 'TEXT'), ('ajuste_altura', 'TEXT'), ('horas_pc', 'INTEGER'), ('uso_notebook', 'TEXT'), ('fecha_relevamiento', 'TEXT'), ('evaluador', 'TEXT'), ('fecha_nacimiento', 'TEXT'), ('puntuacion_edad', 'INTEGER'), ('estado_flujo', 'TEXT'), ('fecha_implementacion', 'TEXT'), ('responsable', 'TEXT'), ('evidencia_url', 'TEXT'), ('fecha_verificacion', 'TEXT'), ('verificado', 'INTEGER'), ('audit_alertas', 'TEXT'), ('intervencion_realizada', 'TEXT'), ('fecha_cierre', 'TEXT'), ('fecha_recordatorio', 'TEXT'), ('pro_condicion_0_100', 'REAL'), ('pro_expo_0_100', 'REAL'), ('pro_vulner_0_100', 'REAL'), ('pro_score_final', 'REAL'), ('pro_condicion_riesgo', 'TEXT'), ('pro_motivos', 'TEXT'), ('salud_evaluador', 'TEXT'), ('salud_fecha', 'TEXT')])
        con.commit()
    def ensure_sst_ergonomia_historial_table(con):
        con.execute("\n            CREATE TABLE IF NOT EXISTS sst_ergonomia_historial(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                personal_id INTEGER NOT NULL,\n                fecha_evento TEXT DEFAULT (datetime('now')),\n                usuario_cambio TEXT,\n                accion_tomar TEXT,\n                puntuacion_puesto INTEGER,\n                promedio REAL,\n                evaluador TEXT,\n                fecha_relevamiento TEXT,\n                observaciones TEXT,\n                cambios_json TEXT,\n                snapshot_json TEXT\n            )\n        ")
        ensure_cols(con, 'sst_ergonomia_historial', [('usuario_cambio', 'TEXT'), ('cambios_json', 'TEXT')])
        con.commit()
    def ensure_sst_control_tables(con):
        con.execute('\n            CREATE TABLE IF NOT EXISTS sst_control_objetivos(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                nombre TEXT NOT NULL,\n                consolidado_ok INTEGER DEFAULT 0,\n                decision_ok INTEGER DEFAULT 0,\n                impl_compra_necesaria TEXT,\n                impl_pedido TEXT,\n                impl_recibido TEXT,\n                impl_ejecucion TEXT,\n                impl_colocacion TEXT,\n                impl_pedido_fecha TEXT,\n                impl_recibido_fecha TEXT,\n                impl_ejecucion_fecha TEXT,\n                impl_colocacion_fecha TEXT,\n                eval_verificado TEXT,\n                eval_observaciones TEXT,\n                eval_cerrado TEXT\n            )\n        ')
        con.execute("\n            CREATE TABLE IF NOT EXISTS sst_control_relevamientos(\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                objetivo_id INTEGER NOT NULL,\n                sede_codigo TEXT NOT NULL,\n                ok INTEGER DEFAULT 0,\n                actualizado_en TEXT DEFAULT (datetime('now')),\n                FOREIGN KEY(objetivo_id) REFERENCES sst_control_objetivos(id)\n            )\n        ")
        con.commit()
    
    

    ensure_sst_general_table(con)
    ensure_sst_plan_tables(con)
    ensure_materiales_table(con)
    ensure_documentos_tables(con)
    asegurar_tabla_limpieza()
    asegurar_tablas_planos()
    asegurar_tabla_aires()
    ensure_sst_ergonomia_table(con)
    ensure_sst_ergonomia_historial_table(con)
    ensure_sst_control_tables(con)
    init_db()
